image: Visual Studio 2019

environment:
  CMAKE_PREFIX_PATH: C:\Qt\5.12\msvc2017\lib\cmake

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - git submodule update --init --recursive

build_script:
  - mkdir build && cd build
  - cmake -G "Visual Studio 16 2019" -A Win32 -DBUILD_QT_FRONTEND=ON -DINSTALL_MUPEN64PLUS=ON -DCMAKE_INSTALL_PREFIX=install ..
  - cmake --build . --config Release
  - cmake --install . --config Release

artifacts:
  - path: build/install
    name: net64-coop-%APPVEYOR_REPO_COMMIT%

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))